  on:
    workflow_dispatch:

  jobs:
    Experiment:
      strategy:
        matrix:
          include:
            - experimentId: 1
            - experimentId: 2
            - experimentId: 3
      runs-on: macos-latest
      steps:
        - name: Set up JDK 17
          uses: actions/setup-java@v4
          with:
            java-version: 17
            distribution: "temurin"
        - name: Download latest version of the validation scripts
          uses: gradle/gradle-enterprise-build-validation-scripts/.github/actions/gradle/download@actions-stable
          with:
            token: ${{ secrets.GITHUB_TOKEN }}