  on:
    workflow_dispatch:

  jobs:
    Experiment:
      strategy:
        matrix:
          include:
            - experimentId: 1
      runs-on: macos-latest
      steps:
        - name: Set up JDK 17
          uses: actions/setup-java@v4
          with:
            java-version: 17
            distribution: "temurin"
        - name: Download latest version of the validation scripts
          uses: gradle/gradle-enterprise-build-validation-scripts/.github/actions/gradle/download@actions-stable
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
#        - name: Run experiment 1
#          uses: gradle/gradle-enterprise-build-validation-scripts/.github/actions/experiment-1@actions-stable
#          env:
#            GRADLE_ENTERPRISE_ACCESS_KEY: "${{ secrets.GE_SOLUTIONS_ACCESS_TOKEN }}"
#          with:
#            gitRepo: ${{ env.GIT_REPO }}
#            tasks: ${{ env.TASKS }}
#            args: ${{ env.ARGS }}
#            gradleEnterpriseUrl: ${{ env.GRADLE_ENTERPRISE_URL }}
#          if: matrix.experimentId == 1
        - name: Run experiment 1
          uses: ./.github/actions/experiment-1-debug
          env:
            GRADLE_ENTERPRISE_ACCESS_KEY: "${{ secrets.GE_SOLUTIONS_ACCESS_TOKEN }}"
          with:
            gitRepo: ${{ env.GIT_REPO }}
            tasks: ${{ env.TASKS }}
            args: ${{ env.ARGS }}
            gradleEnterpriseUrl: ${{ env.GRADLE_ENTERPRISE_URL }}
            debug: true
          if: matrix.experimentId == 1
